"""translate categories

Revision ID: 04a17cf915e7
Revises: 8f1b45a1e9af
Create Date: 2020-10-15 11:59:25.710385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a17cf915e7'
down_revision = '8f1b45a1e9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('de', sa.String(length=30), nullable=True))
    op.add_column('categories', sa.Column('ee', sa.String(length=30), nullable=True))
    op.add_column('categories', sa.Column('en', sa.String(length=30), nullable=True))
    op.add_column('categories', sa.Column('es', sa.String(length=30), nullable=True))
    op.add_column('categories', sa.Column('fi', sa.String(length=30), nullable=True))
    op.add_column('categories', sa.Column('fr', sa.String(length=30), nullable=True))
    op.add_column('categories', sa.Column('ru', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'ru')
    op.drop_column('categories', 'fr')
    op.drop_column('categories', 'fi')
    op.drop_column('categories', 'es')
    op.drop_column('categories', 'en')
    op.drop_column('categories', 'ee')
    op.drop_column('categories', 'de')
    # ### end Alembic commands ###
