"""empty message

Revision ID: 095877936cc0
Revises: b3decc1b33ea
Create Date: 2020-10-27 10:20:48.345711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095877936cc0'
down_revision = 'b3decc1b33ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('fi', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
