"""empty message

Revision ID: 1d077c1e98ed
Revises: 642cecf66789
Create Date: 2020-10-27 10:14:27.370233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d077c1e98ed'
down_revision = '642cecf66789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('et', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('fi', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('categories', 'et')
    # ### end Alembic commands ###
