"""ok

Revision ID: 642cecf66789
Revises: 04a17cf915e7
Create Date: 2020-10-26 15:43:50.599290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642cecf66789'
down_revision = '04a17cf915e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'fi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('fi', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
