"""role

Revision ID: 8f1b45a1e9af
Revises: b5dd54c3fab5
Create Date: 2020-09-04 15:53:28.686861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1b45a1e9af'
down_revision = 'b5dd54c3fab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'manager', 'user', name='roles'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
