"""empty message

Revision ID: ab360a7037f9
Revises: 095877936cc0
Create Date: 2020-10-27 10:23:07.350937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab360a7037f9'
down_revision = '095877936cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('fi', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
