"""empty message

Revision ID: b3decc1b33ea
Revises: 1d077c1e98ed
Create Date: 2020-10-27 10:18:02.750898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3decc1b33ea'
down_revision = '1d077c1e98ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('fi', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
