"""advert category

Revision ID: eab0db9909ed
Revises: 7e4cecce9663
Create Date: 2020-06-29 09:44:51.197437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab0db9909ed'
down_revision = '7e4cecce9663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advert_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advert_id'], ['adverts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advert_category_id'), 'advert_category', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advert_category_id'), table_name='advert_category')
    op.drop_table('advert_category')
    # ### end Alembic commands ###
